ALTER TABLE LoyaltyPoints
    MODIFY COLUMN record_id INT NOT NULL AUTO_INCREMENT,
    MODIFY COLUMN customer_id INT NOT NULL,
    MODIFY COLUMN points DECIMAL(10,2) NOT NULL DEFAULT 0,
    MODIFY COLUMN type ENUM('EARN','REDEEM','ADJUST') NOT NULL DEFAULT 'EARN',
    MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    MODIFY COLUMN expired_at DATE,
    ADD COLUMN status ENUM('ACTIVE','EXPIRED','CANCELLED') NOT NULL DEFAULT 'ACTIVE',
    DROP COLUMN note_temp,
    ADD PRIMARY KEY (record_id);
